### ISSUE TITLE
Export Query type

### ISSUE THREAD

**Issue by Dreamsorcerer** [aio-libs/yarl#1050]
In aiohttp we define `params` which is simply passed to URL.with_query(). We should have this parameter typed to allow the same things, but the type is rather complex:
https://github.com/aio-libs/yarl/blob/efea830d088309214450b359f0d02792ba2eaa50/yarl/__init__.pyi#L18-L22

Therefore, it'd be useful to export this type from yarl in order to be reused.

**Comment by bdraco** [comment]
I think this should be a bit easier to make work now
