### ISSUE TITLE
No way to replace path without replacing query

### ISSUE THREAD

**Issue by Lucretiel** [aio-libs/yarl#111]
The following is unexpected behavior:

```
url1 = URL("http://www.example.com/foo?bar=10")
url2 = url1.with_path("/bar")

assert url1.query = url2.query  # Assertion fails
```

While I understand the design decision to treat the query and fragment components as part of the path, this has left us without an (efficient) way to preserve the query and fragment components when replacing just the path. The only way to do it is:

```
url2 = url1.with_path(new_path).with_query(url1.query_string).with_fragment(url1.fragment)
```

This is a total of 4 extra method calls, at least of which does a lot of unnecessary processing. I'm assuming that there's code out there that depends on this weird behavior, so I'd like to propose and, with permission, implement a new method, `with_just_path`, which replaces the path but leaves the fragment and query the same.

**Comment by asvetlov** [comment]
Did you try `URL.build`?

**Comment by Lucretiel** [comment]
I mean, that would work, but why even have the `with_*` methods in the first place? This seems like it'd fit in well with the other `with` methods.

**Comment by asvetlov** [comment]
Honestly I don't want to blow up URL class with new methods.
Also I suspect your need is very rare: usually query/fragment is described by path, different paths have different allowed query params.
The only exception is passing in query some constant information like security token, it could be done by `url.update_query()` now.

**Comment by Lucretiel** [comment]
My need is in use for a web framework, which is why I'm interested in reducing the amount of unnecessary work implied by `with_query`. In particular, I'm working on django-style path routing where the front of a path is cut off when it's passed to child route views. It's not exactly a very common use case, but I can imagine it'd be common for creating web frameworks based on yarl.

**Comment by asvetlov** [comment]
Thus do you need cutting first path symbols from relative URL?
Make sense.
Maybe create a special method for this case?

**Comment by eternal-sorrow** [comment]
Then `URL.with_host()` should cut off the path, query and fragment altogether. Why the inconsistency? It doesn't make sense.
```python
>>> URL('https://foo.tld/path?a=1#fragment').with_host('bar.tld')
URL('https://bar.tld/path?a=1#fragment')
```

**Comment by apalala** [comment]
It is totally unexpected that `.with_path()` will remove `query`.

**Comment by JP-Ellis** [comment]
Working with this library, and got this unexpected behaviour as well.

Is there any appetite for a PR?

**Comment by trim21** [comment]
is this consider a bug or by design？

**Comment by asvetlov** [comment]
It is a design decision.
I hear the need for path replacement with saving the query though.
We cannot just change the behavior, it will break existing code. What we can do is change `URL.with_path()` method to `URL.with_path(path, *, keep_query=False)`.
Passing `keep_query=True` saves an existing query string.
Does it sound good?

**Comment by trim21** [comment]
maybe also fragment …

**Comment by paul-nameless** [comment]
Hi, I made some changes to support this behavior. Could you please take a look? Thank you!
#1421
