### ISSUE TITLE
[injection] updated URL.join empty path change with 1.9.10

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/yarl#1116]
### Please confirm the following

- [X] I agree to follow the [aio-libs Code of Conduct][CoC]

[CoC]: ../../.github/blob/master/CODE_OF_CONDUCT.md

- [X] I have checked the [current issues][issue search] for duplicates.

[issue search]: ../search?q=is%3Aissue&type=issues

- [X] I understand this is open source software provided for free and that I might not receive a timely response.
- [X] I am positive I am **NOT** reporting a (potential) security
vulnerability, to the best of my knowledge. *(These must be shared by
submitting [this report form][vulnerability report form] instead, if
any hesitation exists.)*

[vulnerability report form]: ../security/advisories/new

- [ ] I am willing to submit a pull request with reporoducers as xfailing test cases or even entire fix. *(Assign this issue to me.)*

### Describe the bug

1.9.10 changed the behavior of URL.join which ended up breaking several calls of ours.  

If you constructed an base URL (same behavior across both versions): 
```python
>>> import yarl
>>> yarl.__version__
'1.9.10'
>>> base = yarl.URL.build(scheme='https', host='localhost', port=443)
>>> base.path
'/'
>>> base._val.path
''
```

(note difference in what is stated as the path and what is stored as the path).

In 1.9.9 if you did a join like so you get the following:
```python
>>> joined = base.join(URL('') / "_msearch")
>>> str(joined)
'https://localhost/_msearch'
>>> joined._val
SplitResult(scheme='https', netloc='localhost', path='/_msearch', query='', fragment='')
```
(note the str of the url patches the stored path)

however the behavior changed in 1.9.10:
```python
>>> joined = base.join(URL('') / "_msearch")
>>> str(joined)
'https://localhost/_msearch'
>>> joined._val
SplitResult(scheme='https', netloc='localhost', path='_msearch', query='', fragment='')
```

note: the strification of the url matches the expected output, however what is stored in the path is now missing the leading slash.  When sent to aiohttp the ends up causing opensearch to not recognize the request and hence breaking existing code.

If this was intended behavior it should not have been done in a patch and a warning issued...however given that the stored path does not match the strification I'd imagine this change in behavior was not intended.

### To Reproduce

1. Tested with python 3.11
2. Run the following code and compare against 1.9.9 and later versions:
```python
import yarl

base = yarl.URL.build(scheme='https', host='localhost', port=443)
(base.join(yarl.URL('') / "_msearch"))._val
```

### Expected behavior

joined url's stored path should contain leading slash

### Logs/tracebacks

```python-traceback
see above
```

### Python Version

```console
Python 3.11.9
```

### multidict Version

```console
Name: multidict
Version: 6.0.5
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /Users/alexmohr/.local/share/virtualenvs/commodities-uyI3VCa_/lib/python3.11/site-packages
Requires: 
Required-by: aiohttp, yarl
```

### yarl Version

```console
Name: yarl
Version: 1.9.10
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
Location: /Users/alexmohr/.local/share/virtualenvs/commodities-uyI3VCa_/lib/python3.11/site-packages
Requires: idna, multidict
Required-by: aiohttp, fbn_async_server
```

### OS

OSX 14.6.1

**Comment by bdraco** [comment]
I think that was an unintentional change from #1082.  Do you have a reproducer that doesn't access `_val`?

**Comment by bdraco** [comment]
```
>>> (base.join(yarl.URL('') / "_msearch")).raw_path
'/_msearch'
```

That should work

**Comment by thehesiod** [comment]
> I think that was an unintentional change from #1082. Do you have a reproducer that doesn't access `_val`?

yep, 1.9.10:
```
>>> (base.join(yarl.URL('') / "_msearch")).path
'_msearch'
```

vs 1.9.9:
```
>>> (base.join(URL('') / "_msearch")).path
'/_msearch'
```

**Comment by bdraco** [comment]
I'll get https://github.com/aio-libs/yarl/pull/1118 merged and prepare a new release shortly

**Comment by bdraco** [comment]
https://github.com/aio-libs/yarl/pull/1119

**Comment by bdraco** [comment]
shortly turned into a bit of an ordeal due to the new upload-artifact/download-artifact breaking changes 

It should hopefully be going now https://github.com/aio-libs/yarl/actions/runs/10747016614 and the wheels should take about one more hour

**Comment by thehesiod** [comment]
really appreciate the quick action on this!

**Comment by bdraco** [comment]
1.10.0 published
