### ISSUE TITLE
Parsing an IPv6 address URL with no port number (e.g. `http://[::1]/`) loses the square brackets

### ISSUE THREAD

**Issue by c3pmark** [aio-libs/yarl#1157]
### Please confirm the following

- [x] I agree to follow the [aio-libs Code of Conduct][CoC]

[CoC]: ../../.github/blob/master/CODE_OF_CONDUCT.md

- [X] I have checked the [current issues][issue search] for duplicates.

[issue search]: ../search?q=is%3Aissue&type=issues

- [X] I understand this is open source software provided for free and that I might not receive a timely response.
- [X] I am positive I am **NOT** reporting a (potential) security
vulnerability, to the best of my knowledge. *(These must be shared by
submitting [this report form][vulnerability report form] instead, if
any hesitation exists.)*

[vulnerability report form]: ../security/advisories/new

- [X] I am willing to submit a pull request with reporoducers as xfailing test cases or even entire fix. *(Assign this issue to me.)*

### Describe the bug

When parsing a URL containing an IPv6 address in square brackets with no port number, the brackets vanish. This was introduced in d5c5ab38; before that, the square brackets were preserved.

I'm pretty sure this is incorrect behavior, but I'm not an expert on URL parsing. If it is a bug, I can work on tests and a PR.

### To Reproduce

```
>>> yarl.URL("http://[::1]")
URL('http://::1')
>>> yarl.URL("http://[2607:f8b0:400b:802::200e]")
URL('http://2607:f8b0:400b:802::200e')
```

### Expected behavior

I expected the brackets to be preserved.
```
>>> yarl.URL("http://[::1]")
URL('http://[::1]')
>>> yarl.URL("http://[2607:f8b0:400b:802::200e]")
URL('http://[2607:f8b0:400b:802::200e]')
```

### Logs/tracebacks

```python-traceback
N/A
```

### Python Version

```console
$ python --version
Python 3.12.6
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.0.5
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /usr/lib64/python3.12/site-packages
Requires:
Required-by: aiohttp, yarl
```

### yarl Version

```console
Git master as of bf2ced70

$ python -m pip show yarl
Name: yarl
Version: 1.12.2.dev0
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
Location: /home/mark/.local/lib/python3.12/site-packages
Editable project location: /home/mark/src/yarl
Requires: idna, multidict
Required-by: aiohttp
```

### OS

Linux (Fedora 40)

### Additional context

I don't believe the resulting URLs are valid, although I could be wrong in this case. They aren't parseable by yarl, in any case.

```
>>> yarl.URL(str(yarl.URL("http://[::1]/")))
Traceback (most recent call last):
  File "/home/mark/src/yarl/yarl/_url.py", line 1051, in _split_netloc
    port = int(port_str)
           ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ':1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mark/src/yarl/yarl/_url.py", line 262, in __new__
    username, password, host, port = cls._split_netloc(val[1])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mark/src/yarl/yarl/_url.py", line 1053, iIP URLn _split_netloc
    raise ValueError("Invalid URL: port can't be converted to integer")
ValueError: Invalid URL: port can't be converted to integer
```

**Comment by bdraco** [comment]
The []s should be kept AFAICT

https://datatracker.ietf.org/doc/html/rfc2732#section-2

**Comment by bdraco** [comment]
@c3pmark Thanks for the report, https://github.com/aio-libs/yarl/pull/1158 will fix this

**Comment by bdraco** [comment]
1.13.0 released

**Comment by c3pmark** [comment]
Thanks so much, @bdraco - not only for looking at this so fast but for fixing it right away too! I've made a donation to the Maui Food Bank in your name :heart:
