### ISSUE TITLE
/-joining of urls can produce multiple slashes

### ISSUE THREAD

**Issue by mgedmin** [aio-libs/yarl#12]
```python
>>> from yarl import URL
>>> URL('http://example.com/api/') / 'sub/path'
URL('http://example.com/api//sub/path')
```

Should that double slash be there?

Other corner cases:

```python
>>> URL('http://example.com/api') / '/sub/path'
URL('http://example.com/api//sub/path')
>>> URL('http://example.com/api/') / '/sub/path'
URL('http://example.com/api///sub/path')
```

These examples work the way I expect:

```python
>>> URL('http://example.com/') / 'sub/path'
URL('http://example.com/sub/path')
>>> URL('http://example.com') / 'sub/path'
URL('http://example.com/sub/path')
```

These do not:

```python
>>> URL('http://example.com/') / '/sub/path'
URL('http://example.com//sub/path')
>>> URL('http://example.com') / '/sub/path'
URL('http://example.com//sub/path')
```

Bug or explicit design decision?

**Comment by asvetlov** [comment]
Thank for pointing on quirks out!
`URL('http://example.com/api/') / 'sub/path'` shouldn't produce double slash.
But appending a path starting from slash should be forbidden explicitly I think.
For `URL('http://example.com/api') / '/sub/path'` case the right part looks like an absolute path, appending absolute path to absolute URL is wrong from my perspective.

Would you make a PR with fix?

**Comment by mgedmin** [comment]
I'm ambivalent about `URL(...) / '/subpath/starting/with/a/slash'`.  Sometimes it seems to make sense, e.g. when you're considering a WSGI application mounted at some URL prefix, and you're thining about API endpoints in terms of `/path/from/the/app/root`.  I don't personally care strongly about it.  (I don't in fact use yarl anywhere yet. :wink:)

**Comment by asvetlov** [comment]
Let's forbid it now.
If we'll change our mind in future we may relax the rule without any backward incompatibility issue.
But restricting is much more painful process :)

**Comment by mgedmin** [comment]
Do you want me to update my PR, or ... ?

(I'm feeling kind of lazy.)

**Comment by asvetlov** [comment]
If you would to update it or create new one with preventing absolute paths -- please go ahead.
If not -- I'll just merge existing code and will try to find a time for fixing by myself.

**Comment by mgedmin** [comment]
Go ahead and merge then.

Thanks!
