### ISSUE TITLE
Remove the need to set ENABLE_HYPOTHESIS_TESTS in tests

### ISSUE THREAD

**Issue by bdraco** [aio-libs/yarl#1262]
https://github.com/aio-libs/yarl/blob/b64f2318df91e295f6fc4eb706794361890ad83d/.github/workflows/ci-cd.yml#L314

> https://cibuildwheel.pypa.io/en/stable/options/#overrides would've solved the problem better, FYI. You could override the pytest command with one including -m 'not hypothesis' (having configured the corresponding marker in the tests).

suggestion by webknjaz

**Comment by webknjaz** [comment]
> You could override the pytest command with one including -m 'not hypothesis'

Or set the same via `PYTEST_ADDOPTS`.
