### ISSUE TITLE
Can not use subclass' of int for query={'key': <int subclass>}

### ISSUE THREAD

**Issue by jamespeterschinner** [aio-libs/yarl#129]
Should be able to pass subclass' of both `str` and `int` to `URL` `query` parameter.

Example:

    from yarl import URL
    
    class Example(int):
        def __new__(cls, value):
            return super().__new__(cls, value)
    
    url = URL.build(scheme='https', host='github.com',
                    path='/aio-libs/yarl/search?utf8=%E2%9C%93&q=elif+type%28v%29+%3D%3D+int%3A+&type=',
                    query={'test': Example(0)})
    
    print(url)

**Comment by asvetlov** [comment]
Subclass forbidding is deliberate design choice.
If you need `int` subclassing support (like `bool`) -- please serialize these objects explicitly before passing into `yarl`.

**Comment by jamespeterschinner** [comment]
No problem
