### ISSUE TITLE
Explicit port 0 replaced with default port

### ISSUE THREAD

**Issue by gmacon** [aio-libs/yarl#1408]
### Please confirm the following

- [X] I agree to follow the [aio-libs Code of Conduct][CoC]

[CoC]: ../../.github/blob/master/CODE_OF_CONDUCT.md

- [X] I have checked the [current issues][issue search] for duplicates.

[issue search]: ../search?q=is%3Aissue&type=issues

- [X] I understand this is open source software provided for free and that I might not receive a timely response.
- [X] I am positive I am **NOT** reporting a (potential) security
vulnerability, to the best of my knowledge. *(These must be shared by
submitting [this report form][vulnerability report form] instead, if
any hesitation exists.)*

[vulnerability report form]: ../security/advisories/new

- [X] I am willing to submit a pull request with reporoducers as xfailing test cases or even entire fix. *(Assign this issue to me.)*

### Describe the bug

If a URL has an explicit port of `0` and a scheme with a default port (such as `http`), then the `port` and `explicit_port` attributes disagree on what the port is.

### To Reproduce

```
import yarl
u = yarl.URL("http://a.co:0")
assert u.port == u.explicit_port
```

### Expected behavior

If `explicit_port` is not `None`, then `port` should be the same as `explicit_port`.

### Logs/tracebacks

```python-traceback
Python 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yarl
>>> u = yarl.URL("http://a.co:0")
>>> assert u.port == u.explicit_port
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
>>> u.port
80
>>> u.explicit_port
0
```

### Python Version

```console
$ python --version
Python 3.10.12
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.1.0
Location: $PWD/.venv/lib/python3.10/site-packages
Requires: typing-extensions
Required-by: yarl
```

### propcache Version

```console
$ python -m pip show propcache
Name: propcache
Version: 0.2.0
Location: $PWD/.venv/lib/python3.10/site-packages
Requires:
Required-by: yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.17.2.dev0
Location: $PWD/.venv/lib/python3.10/site-packages
Editable project location: $PWD
Requires: idna, multidict, propcache
Required-by:
$ git describe
v1.17.1-1-gdfc41db
```

### OS

Ubuntu 22.04

### Additional context

I discovered this because Hypothesis can generate such a URL from its `hypothesis.provisional.urls` strategy. I think yarl's implementation of `port` (as `self.explicit_port or self._default_port`) is wrong because the URL grammar permits the port to be 0 (the production is just `port = *DIGIT`), but I can't think of a situation where a URL with port 0 would be useful.

**Comment by webknjaz** [comment]
Thanks for the report! Outside of URLs, port 0 may have different semantics assigned. For example, it can be a so-called "ephemeral port" that is passed into the socket bind syscalls and then the kernel assigns an unoccupied port that nobody claimed, at which point it turns into a concrete port with a non-zero number.

I can imagine that someone may want to represent a pre-binding URL for logging purposes. Or for when an interactive app doesn't bind to a port until a user clicks the button.

I can also imagine `0` having different semantics for non-HTTP URLs (yarl is agnostic, after all).

So I'd say — send us an xfailing test and perhaps some Hypothesis tests, for starters.

No rush, though — we're leading an aiohttp sprint day on Saturday and this might be a good issue for the participants to look into.

**Comment by ajsanchezsanz** [comment]
We are looking into this.

**Comment by webknjaz** [comment]
It doesn't look like anybody picked this up...

**Comment by asvetlov** [comment]
I can imagine the only usage for port 0: make an url that listens on any available port.
Honestly I never met this notation in real life before this issue.
