### ISSUE TITLE
Support uppercase characters in host

### ISSUE THREAD

**Issue by xZise** [aio-libs/yarl#1441]
### Please confirm the following

- [X] I agree to follow the [aio-libs Code of Conduct][CoC]

[CoC]: ../../.github/blob/master/CODE_OF_CONDUCT.md

- [X] I have checked the [current issues][issue search] for duplicates.

[issue search]: ../search?q=is%3Aissue&type=issues

- [X] I understand this is open source software provided for free and that I might not receive a timely response.
- [X] I am positive I am **NOT** reporting a (potential) security
vulnerability, to the best of my knowledge. *(These must be shared by
submitting [this report form][vulnerability report form] instead, if
any hesitation exists.)*

[vulnerability report form]: ../security/advisories/new

- [ ] I am willing to submit a pull request with reporoducers as xfailing test cases or even entire fix. *(Assign this issue to me.)*

### Describe the bug

When using uppercase characters in the hostname they get reported as invalid:

```
>>> URL.build(scheme="http", host="A", port=port, path="/")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\yarl\_url.py", line 386, in build
    _host = _encode_host(host, validate_host=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\yarl\_url.py", line 1496, in _encode_host
    raise ValueError(
ValueError: Host 'A' cannot contain 'A' (at position 0)
>>> URL.build(scheme="http", host="a", port=port, path="/")
URL('http://a/')
```

It appears to me, that there needs to be a conversion into lowercase, for example the [`host`-property](https://yarl.aio-libs.org/en/latest/api/#yarl.URL.host) says it gets converted to lowercase (which is the case when using `__init__()`) and the comment at `NOT_REG_NAME` mentions that it only accepts lowercase ASCII values:
```
# this pattern matches anything that is *not* in those classes. and is only used
# on lower-cased ASCII values.
```

When using a non-ASCII string with host, it gets encoded so it seems weird that ASCII uppercase strings aren't "encoded" into lowercase. There is #386, but there it is using `__init__()` which works correctly.

### To Reproduce

1. Install yarl
2. Call `yarl.URL.build(scheme="http", host="A", port=port, path="/")`

### Expected behavior

A valid URL which is identical to the build URL using the lowercase host.

### Logs/tracebacks

```python-traceback
>>> URL.build(scheme="http", host="A", port=port, path="/")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\yarl\_url.py", line 386, in build
    _host = _encode_host(host, validate_host=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\yarl\_url.py", line 1496, in _encode_host
    raise ValueError(
ValueError: Host 'A' cannot contain 'A' (at position 0)
>>> URL.build(scheme="http", host="a", port=port, path="/")
URL('http://a/')
```

### Python Version

```console
$ python --version
Python 3.12.2
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.1.0
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: ..\Lib\site-packages
Requires:
Required-by: yarl
```

### propcache Version

```console
$ python -m pip show propcache
Name: propcache
Version: 0.2.0
Summary: Accelerated property cache
Home-page: https://github.com/aio-libs/propcache
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
Location: ..\Lib\site-packages
Requires:
Required-by: yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.18.0
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
Location: ..\Lib\site-packages
Requires: idna, multidict, propcache
Required-by:
```

### OS

Windows 10

**Comment by bdraco** [comment]
We do lowercase the host after the validation so its an order problem.

**Comment by bdraco** [comment]
This is a regression introduced in https://github.com/aio-libs/yarl/pull/954

**Comment by bdraco** [comment]
#1442 will fix this.

Unfortunately we cannot do a release right now due to https://github.com/pypa/gh-action-pypi-publish/issues/30

**Comment by bdraco** [comment]
It looks like whatever problem that was slowing down the uploads enough to fail has been resolved a propcache just released successfully. I'll try to get a .3 published with this fix today

**Comment by bdraco** [comment]
1.18.3 publishing now. 🤞 that the upload problem doesn't bite us

https://github.com/aio-libs/yarl/actions/runs/12108501591

**Comment by bdraco** [comment]
1.18.3 now available with the fix
