### ISSUE TITLE
Same parts, but different __str__

### ISSUE THREAD

**Issue by netstuff** [aio-libs/yarl#153]
```
In: str(yarl.URL('http://localhost')), yarl.URL('http://localhost').parts
Out: ('http://localhost', ('/',))

In: str(yarl.URL('http://localhost').with_path('/')), yarl.URL('http://localhost').parts
Out: ('http://localhost/', ('/',))
```

The case is that `SplitResult.path` attribute contains (or not) passed `'/'` value. But at first glance it looks like a bug. 

Maybe, `yarl.URL.parts` must not returns `'/'` if `SplitResult.path` is empty?

Thank you.

**Comment by asvetlov** [comment]
The difference is 
```
In [14]: URL('http://localhost').parts
Out[14]: ('/',)

In [15]: URL('http://localhost/').parts
Out[15]: ('/', '')
```
In last case parts contain extra empty path segment.

Why is it problem for you?
Equality check works as expected:
```

In [16]: URL('http://localhost/') == URL('http://localhost')
Out[16]: True
```

**Comment by netstuff** [comment]
Thanks, Andrew!

I wanna tell about it:
```
URL('http://localhost').path != URL('http://localhost')._val.path
```

Therefore:
```
str(URL('http://localhost')) != str(URL('http://localhost'))
```

but, yes
```
URL('http://localhost/') == URL('http://localhost')
```

Is it normally?

**Comment by asvetlov** [comment]
I have no strong opinion.
But going this way further `http://localhost` should be converted into `http://localhost/`.
Or maybe reverse:  `http://localhost/` -> `http://localhost`, like browsers do.

More I think more inclined to the second option: remove bare root slash from path always.

**Comment by netstuff** [comment]
Yes, I did it already :)
Thank you, Andrew.
