### ISSUE TITLE
_PyQuoter not quoting correctly 

### ISSUE THREAD

**Issue by diogommartins** [aio-libs/yarl#162]
I've found a bug that only occurs on the pure python implementation of url quoting. Reproducing the bug is quite easy:

``` python
assert _PyQuoter("% C") == "%25%20C" 
```

It fails to quote it correctly and if just returns `% C`, while `urllib` does it correctly

```python
from urllib.parse import quote

assert quote("% C") == "%25%20C"
```

It fails for every character <= "F" on the ascii table and the reason is that the quoter expects a ValueError that isnt raised by the following piece of code:

``` python
try:
    unquoted = chr(int(pct[1:].decode('ascii'), base=16))
except ValueError:
    ret.extend(b'%25')
    pct = b''
    idx -= 2
    continue
```

**Comment by asvetlov** [comment]
Nice catch!
Would you provide a Pull Request for fix?

**Comment by diogommartins** [comment]
When i noticed the error my first intemption was to open the issue with a PR, but i wasnt able to figure out a quick fix for the problem because i dindnt understood a bunch of implementation details and i would need to rewrite a bunch of code, which i judged not to be a very good idea. If thats not the case, let me know and i can give it a try.

One of the things i dont understand about `yarl` is the choice of having it's own implentation of `quote` and `unquote` which is only used as a fallback for the cython implementation. Since python already provides a `quote` and `unquote` at `urllib` wouldn't be better to use it when possible ?

**Comment by asvetlov** [comment]
The main difference in behavior: yarl quoter actually *requotes* the argument by quoting unsafe characters but unquoting safe-but-quoted ones. The definition for safe-but-quoted depends on context.
For example `'/'` is safe for unquoting in username but bu forbidden in path.
That's why accepted args and internal logic is very different.

**Comment by asvetlov** [comment]
Thanks for report!

**Comment by diogommartins** [comment]
Thanks a lot ! 👍
