### ISSUE TITLE
Expose netloc as attribute

### ISSUE THREAD

**Issue by achimnol** [aio-libs/yarl#176]
It is often useful to distinguish the target URL's host including port numbers, not just hostname.
I suggest making a public property `netloc` that returns `self._val.netloc`.

**Comment by asvetlov** [comment]
`netloc` also contains user/password if any. Do you need all of them?

**Comment by asvetlov** [comment]
Should it be in PCT-encoded or decoded form?

Also what is `distinguish` meaning? `url1 == url2` check?

**Comment by asvetlov** [comment]
`url1.origin() == url2.origin()`?

**Comment by achimnol** [comment]
`origin()` could be an alternative, but I need exactly "host:port" form excluding the protocol scheme part.
Anyway, as `netloc` is not what I expected so closing this issue.
I think simply `f"{u.host}:{u.port}"` should be sufficient for my use case.

**Comment by asvetlov** [comment]
Ok
