### ISSUE TITLE
ImportError on TYPE_CHECKING

### ISSUE THREAD

**Issue by GDICommander** [aio-libs/yarl#189]
Hello,

I have aiohttp 2.3.10 and I have yarl 1.2.0, which got released 3 hours ago. I am using them on Windows. When importing aiohttp, which imports yarl, I have this error:

```
  File "F:\Git\ubi_leviathan\ubi_leviathan\utils.py", line 3, in <module>
    import aiohttp
  File "f:\git\ubi_leviathan\.tox\py35\lib\site-packages\aiohttp\__init__.py", line 6, in <module>
    from .client import *  # noqa
  File "f:\git\ubi_leviathan\.tox\py35\lib\site-packages\aiohttp\client.py", line 13, in <module>
    from yarl import URL
  File "f:\git\ubi_leviathan\.tox\py35\lib\site-packages\yarl\__init__.py", line 11, in <module>
    from .quoting import _Quoter, _Unquoter
  File "f:\git\ubi_leviathan\.tox\py35\lib\site-packages\yarl\quoting.py", line 3, in <module>
    from typing import Optional, TYPE_CHECKING, cast
ImportError: cannot import name 'TYPE_CHECKING'
```

Can this import error be fixed in yarl?

Have a good day!

**Comment by asvetlov** [comment]
Thanks for reporting.
`TYPE_CHECKING` is available in Python 3.5.2+ (https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING)
Since aiohttp 3.x requires Python 3.5.3+ I think the pinning minimal supported Python version is a good choice.
For you I suggest to use `yarl==1.1.2`, there is no sense for yarl to support old Python versions.

**Comment by GDICommander** [comment]
All right, big thanks for the explanation and the quick answer! :)
I am indeed using Python 3.5.1 and I will upgrade on my end.

**Comment by asvetlov** [comment]
Yep, I highly recommend Python version, on Windows it is pretty easy.

**Comment by asvetlov** [comment]
Python is pinned by ea1a5e6

Close the issue.

**Comment by pquentin** [comment]
For what it's worth, Ubuntu 16.04 LTS only provides Python 3.5.2, which means we have to require yarl<=1.2.0 to fix aiohttp 2.x installation on Ubuntu 16.04. But please don't change anything, using an old Python/Ubuntu is our problem, not yours!

**Comment by asvetlov** [comment]
Please pin yarl in your requirements.
Or update to the latest LTS :)

**Comment by pquentin** [comment]
Thanks! Yes, we pinned the dependency, and will update to the latest LTS at some point.
