### ISSUE TITLE
`if type(val) is str` is a bit too strict

### ISSUE THREAD

**Issue by hynek** [aio-libs/yarl#190]
It makes sense to use a subclass of str for example if I want to put a secret into a class but want to censor the repr: https://github.com/hynek/environ_config/blob/69b1c8ab25fde3c20fa21de1a044e30760c86d36/src/environ/secrets.py#L114-L124

This breaks with the latest versions.

**Comment by asvetlov** [comment]
Hackish.
I can do `str(val)` if the type is not strict `str` but derived class.
You should understand that it implies a little performance penalty.

**Comment by hynek** [comment]
Why not `isinstance(val, str)`? That slow?

**Comment by hynek** [comment]
I only need this outside of aiohttp to parse URLs from secrets so performance is not an issue. Would it be perf-neutral for you if you added `or isinstance()`? It’s lazily evaluated so it shouldn’t be a measurable slow down?

**Comment by asvetlov** [comment]
Done in yarl 1.2.3

**Comment by hynek** [comment]
Amazing, thank you!
