### ISSUE TITLE
Switch to semantic versioning

### ISSUE THREAD

**Issue by vasa-chi** [aio-libs/yarl#193]
As far as I can tell, version 1.2.0 switched to python>=3.5.2 from python>=3.4.0.
I think such changes should cause a major version bump.

**Comment by asvetlov** [comment]
How it can help you *right now*? 
Despite the fact that 1.2.0 is already released.

**Comment by vasa-chi** [comment]
Well, it can't help me now :) I just think that in future such changes should me in major releases.

**Comment by asvetlov** [comment]
Let's close the issue and consider a major version bump for the next yarl release
