### ISSUE TITLE
Missing type annotations in cached_property

### ISSUE THREAD

**Issue by scottbelden** [aio-libs/yarl#195]
As of v1.2.0 the type annotations for `cached_property` in the pyi file are as follows:

```python
class cached_property:
    def __init__(self, wrapped: Any) -> None: ...

    def __get__(self, inst: cached_property, owner) -> Any: ...

    def __set__(self, inst: cached_property, value) -> None: ...
```

`owner` and `value` don't have types. I'm not sure if I'm invoking `mypy` incorrectly, but on v1.1.1 I didn't have any trouble and now (with v1.2.0+) I get the following errors:

```
/usr/local/lib/python3.6/dist-packages/yarl/__init__.pyi:97: error: Function is missing a type annotation for one or more arguments
/usr/local/lib/python3.6/dist-packages/yarl/__init__.pyi:99: error: Function is missing a type annotation for one or more arguments
```

I'm assuming `value` is an `Any` type, but I'm not sure about `owner` as I didn't even see it being used in the source code. I don't mind making a PR if you can let me know what the type of `owner` should be (and confirm the type of `value`).

**Comment by asvetlov** [comment]
Thanks for the report.
The fix is trivial, I've published yarl 1.2.4
