### ISSUE TITLE
Implement join()

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/yarl#2]
https://tools.ietf.org/html/rfc3986.html

**Comment by jettify** [comment]
is it alternative to https://hg.python.org/cpython/file/dfb61cd916e3/Lib/urllib/parse.py#l469?

**Comment by asvetlov** [comment]
Implemented exactly by `urllib.parse.urljoin()`

**Comment by asvetlov** [comment]
The ship has sailed, sorry.
