### ISSUE TITLE
Running setup.py fails with LC_ALL=C

### ISSUE THREAD

**Issue by keis** [aio-libs/yarl#20]
When running `setup.py` in an environment with LC_ALL=C (or anything besides utf-8) it stops with a UnicodeDecodeError when reading the README.

Changing `read()` to explicitly set the encoding to utf-8 seems to fix this.

**Comment by asvetlov** [comment]
Try yarl==0.6.0 :)

**Comment by keis** [comment]
Yep that fixed the issue. Thx :smile_cat:
