### ISSUE TITLE
Quote method raises on some nasty strings

### ISSUE THREAD

**Issue by Goobs** [aio-libs/yarl#21]
I'm writing REST APIs using Aiohttp. I test requests by passing naughty strings from here: https://github.com/minimaxir/big-list-of-naughty-strings

Before including Yarl into Aiohttp tests passed properly. But after upgrading to Aiohttp 1.1.2 Yarl began to raise errors. Here are some cases:

```
<script src="\\%(jscript)s"></script>
http://a/%%30%30
1;DROP TABLE users  // this one is parsed as int
%x('ls -al /')
%*.*s
```

**Comment by asvetlov** [comment]
Thanks you for report. Do you mean exceptions like `ValueError: Unallowed PCT %*.`?

**Comment by Goobs** [comment]
> Thanks you for report. Do you mean exceptions like ValueError: Unallowed PCT %*.?

Yes, exactly.

**Comment by orf** [comment]
Hey, I'm running into this as well. My query string:

`Train%27%29%20and%20string-length%28%28substring-before%28concat%28%270123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ%21%22%23%24%25%26%27%2C%22%27%22%2C%27%28%29%2A%2B%2C-.%2F%3A%3B%3C%3D%3E%3F%40%5B%5C%5D%5E_%60%7B%7C%7D%7E%27%29%2C%27h%27%29%29%29%3D7%20and%20string%28%271%27%3D%271'`

Decoded it should be:

`Train') and string-length((substring-before(concat('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&',"'",'()*+,-./:;<=>?@[\]^_`{|}~'),'h')))=7 and string('1'='1`

**Comment by alex-cg1** [comment]
Hi guys,

Is there any estimation of when it will be fixed? May be we could just use urllib.parse.urlencode inside yarl as a temprorary solution?

**Comment by fafhrd91** [comment]
i added non strict mode (default), in that case `yarl` quote just `%` symbol. i am not sure if it fixes all problems.

@orf you example already works with yard master

i will release new aiohttp version soon with new yarl.

**Comment by fafhrd91** [comment]
@Goobs could you check if master works for you

**Comment by fafhrd91** [comment]
well, I guess everything works
