### ISSUE TITLE
AttributeError: module 'idna' has no attribute 'encode'

### ISSUE THREAD

**Issue by burtgulash** [aio-libs/yarl#236]
Using python3.7. Noticed this today when aiohttp started failing on basic http requests.

```
import yarl
yarl.URL("https://google.com")
```

Traceback:
```
Traceback (most recent call last):
  File "/tmp/venv/lib/python3.7/site-packages/yarl/__init__.py", line 639, in _encode_host
    ip = ip_address(ip)
  File "/usr/lib/python3.7/ipaddress.py", line 54, in ip_address
    address)
ValueError: 'google.com' does not appear to be an IPv4 or IPv6 address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/bug.py", line 2, in <module>
    yarl.URL("https://google.com")
  File "/tmp/venv/lib/python3.7/site-packages/yarl/__init__.py", line 171, in __new__
    encode=True)
  File "/tmp/venv/lib/python3.7/site-packages/yarl/__init__.py", line 656, in _make_netloc
    ret = cls._encode_host(host)
  File "/tmp/venv/lib/python3.7/site-packages/yarl/__init__.py", line 642, in _encode_host
    host = idna.encode(host, uts46=True).decode('ascii')
AttributeError: module 'idna' has no attribute 'encode'
```

**Comment by asvetlov** [comment]
Most likely you shadow the module by `idna.py` in the local folder.
Check
```
import idna
print(idna.__file__)
```

**Comment by burtgulash** [comment]
Not sure what it was, but I no longer have the problem. Can be closed.

**Comment by Civmwa** [comment]
@burtgulash @asvetlov getting exact same error when trying to convert a python Twint file to Exe via cx_freeze. Do you know what it is? I'm using python 3.6.5, Windows 10 64 bit
![twint to exe using cx_freeze error](https://user-images.githubusercontent.com/38909818/45673346-24355000-bb33-11e8-9f3b-b9cc92b9c85c.PNG)

**Comment by asvetlov** [comment]
What `idna` package did you get from?

**Comment by Civmwa** [comment]
> What `idna` package did you get from?

I pip installed it

**Comment by Civmwa** [comment]
@asvetlov this is the idna_ssl.py . I have 3 other applications and i've never gotten any errors when making it to an exe file. This particular instance has me confused.

![idna_ssl](https://user-images.githubusercontent.com/38909818/45675754-b8ee7c80-bb38-11e8-8002-da6f44bd7517.PNG)
