### ISSUE TITLE
There are 3 failed tests in release v1.2.6

### ISSUE THREAD

**Issue by gyermolenko** [aio-libs/yarl#248]
Python 3.6.6 / yarl 1.2.6 (also tried with the one from master)
For example:
`$ pytest tests/test_quoting.py::test_quote_fastpath_safe`
```
    def test_quote_fastpath_safe():
        s1 = '/path/to'
        s2 = _Quoter(safe='/')(s1)
>       assert s1 is s2
E       AssertionError: assert '/path/to' is '/path/to'

tests/test_quoting.py:335: AssertionError
```
Am I doing something wrong?
Comparison with `==` gives True, do we need `is` in this case?

**Comment by gyermolenko** [comment]
Ok, I was wrong and probably didn't have Cython installed (maybe I did `pip install -e .` instead of `-r requirements/dev.txt` or something).
After I recreated venv - the problem disappeared.

**Comment by asvetlov** [comment]
Good.
