### ISSUE TITLE
Allow scheme replacement for relative urls

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/yarl#280]
`URL('path/to').with_scheme('http')` should work.
Now it produces `scheme replacement is not allowed for relative URLs`

**Comment by mjpieters** [comment]
File URLs that are absolute are also being blocked from updating the scheme:

```
>>> URL('file:///absolute/path').with_scheme('file')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/.../lib/python3.7/site-packages/yarl/_url.py()", line 794, in with_scheme
    raise ValueError("scheme replacement is not allowed for relative URLs")
ValueError: scheme replacement is not allowed for relative URLs
```

**Comment by bdraco** [comment]
The `http` case is correct because the host is not allowed to be undefined for `host` see https://github.com/aio-libs/yarl/issues/821

The `file` case isn't correct though
