### ISSUE TITLE
Query parameters not compared independent of order

### ISSUE THREAD

**Issue by linuxdaemon** [aio-libs/yarl#288]
In a majority of cases `URL('http://example.com/?foo=bar&test=1')` should be equivalent to `URL('http://example.com/?test=1&foo=bar')`, but they are treated as unique and there does not seem to be any extra methods for an order-independent comparison. I've had to do something similar to `url.with_query(MultiDict(sorted(url.query.items())))` to both `URL` objects before comparing them.

A method on the `URL` object to do this sort of comparison would be quite useful, or maybe even implementing it in the normal comparison methods.

**Comment by asvetlov** [comment]
By the standard, order or query values *does* matter.
Moreover, `URL('http://example.com/?foo=bar&foo=baz')` and `URL('http://example.com/?foo=baz&foo=bar')` are different URLs.
The default behavior should be not changed.

If sorting by order works for you -- that's fine. You can do it manually without the library modification.
If you want to propose a new comparison method -- please elaborate the new API first. How should it look like?

**Comment by linuxdaemon** [comment]
I was thinking a method like `URL.unify()` to 'unify' the URL format by converting it to a standard form, with like empty or default url components either always added or always removed, ensuring a consistent order with the parameters, stuff like that. My main use case for this so far is in testing a function which generates a URL with query parameters formed from a dict, as testing on different python versions produces different orders.

**Comment by asvetlov** [comment]
I'm sorry, but `URL.unify()` is out of the project scope.
You can write a helper for dict sorting in your project easy though.
