### ISSUE TITLE
URL path with "/../"

### ISSUE THREAD

**Issue by kkaiser** [aio-libs/yarl#297]
yarl==1.2.6 converts a URL like https://www.example.com/../example.jpg to https://www.example.com/example.jpg just fine.

In yarl==1.3.0 that was changed and now throws a ValueError instead.

```python
>>> from yarl import URL
>>> URL('https://www.example.com/../example.jpg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kkaiser/.pyenv/versions/ocean_ai/lib/python3.7/site-packages/yarl/__init__.py", line 174, in __new__
    cls._validate_authority_uri_abs_path(host=host, path=path)
  File "/Users/kkaiser/.pyenv/versions/ocean_ai/lib/python3.7/site-packages/yarl/__init__.py", line 623, in _validate_authority_uri_abs_path
    "Path in a URL with authority " "should start with a slash ('/') if set"
ValueError: Path in a URL with authority should start with a slash ('/') if set
```

Should that be the expected behaviour? It was already closed once: https://github.com/aio-libs/yarl/issues/84

**Comment by Soniyanayak51** [comment]
Hi, is this issue still open?

**Comment by asvetlov** [comment]
I think  https://www.example.com/../example.jpg  is an invalid path; there is no parent folder in `/../example.jpg` path context.

**Comment by kkaiser** [comment]
It is invalid but unfortunately appears on some websites that is why all browsers seem to convert it. Shouldn't yarl do the same?

**Comment by asvetlov** [comment]
yarl shouldn't be as forgiving as a human-oriented web browser.
Consider it as dividing by zero.
