### ISSUE TITLE
Yarl reuse _cache on with_ and truediv methods

### ISSUE THREAD

**Issue by Reskov** [aio-libs/yarl#314]
I am interested on a performance tip with `idna` reusage. Can we reuse `_cache` for host property, not always but in most cases?

### Long Story

So basically we have
```
class URL:
...
 @cached_property
    def host(self):
        ...
        try:
            return idna.decode(raw.encode("ascii"))
        except UnicodeError:  # e.g. '::1'
            return raw.encode("ascii").decode("idna")
...
```

Also it is not new that `yarl.with_` methods always construct a new instance of `URL` class, therefore doesn't reuse cached properties.

I start digging from `aioelasticsearch` package, real example from package
```
 url = (self.base_url / url.lstrip('/')).with_query(params)
```

So `self.base_url.host` can be resolved and probably reused once, on the other hand if new URL was constructed, it will recall `idna` once again lazily on `host` property get. 
Is this expected behaviour?

### Benchmark check, that `idna` is not free
```
import timeit


python_setup = """\
from yarl import URL
u = URL('http://127.0.0.1')
u.host
"""


raw_with_query = timeit.timeit("n=u.with_query('')", python_setup)

print("Python resolve host: {:.3f} sec".format(
    timeit.timeit("u.with_query('').host",
                  python_setup) - raw_with_query))

print("Python with cache copying: {:.3f} sec".format(
    timeit.timeit("n=u.with_query('')\nn._cache=u._cache\nn.host",
                  python_setup)-raw_with_query))

# I know that `n._cache=u._cache` is not correct :)
# Python resolve host: 30.085 sec
# Python with cache copying: 0.130 sec
```

Is there any reason to do not reuse `_cache` for `host`?

**Comment by asvetlov** [comment]
Addressed by #476
