### ISSUE TITLE
Incorrect parsing of query parameters with %3B (;) inside

### ISSUE THREAD

**Issue by shturman** [aio-libs/yarl#34]
Some test below:

```python
u = yarl.URL('/?user_agent=Mozilla%2F5.0+%28iPhone%3B+CPU+iPhone+OS+10_1_1+like+Mac+OS+X%29+AppleWebKit%2F602.2.14+%28KHTML%2C+like+Gecko%29+Mobile%2F14B100')
assert len(u.query.items()) == 1
```

But I'm getting 2 params.

**Comment by asvetlov** [comment]
I don't follow where do you have two params?

**Comment by shturman** [comment]
assert is failing due to 
```python 
len(u.query.items()) == 2
```

**Comment by asvetlov** [comment]
Got it.
Thank you for report

**Comment by asvetlov** [comment]
Well, that's how [`urllib.parse.parse_sql`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.parse_qsl) works: split on both `&` and `;`.

Not sure if this behavior should be fixed.

**Comment by shturman** [comment]
But that's why ; was encoded with %3B.
The same way I can encode & with %26 and it works perfect. But with ; is not.

**Comment by asvetlov** [comment]
Sorry for my stupidity.
I'll fix it ASAP.

**Comment by shturman** [comment]
np

**Comment by shturman** [comment]
Any updates on this issue? aiohttp query parsing works incorrectly due to it (

**Comment by fafhrd91** [comment]
i will push new release today
