### ISSUE TITLE
Adopt pytest-nunit tool

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/yarl#355]
https://github.com/aio-libs/yarl/pull/353#discussion_r330262147

At least it worth trying

**Comment by tonybaloney** [comment]
You can give `pytest-azurepipelines` a go as it removes a lot of the boilerplate for pytest/azure

Most of the advanced functionality comes from using this extension in the UI https://marketplace.visualstudio.com/items?itemName=AnthonyShaw.vss-pytest

**Comment by asvetlov** [comment]
It looks awesome but when I've tried to apply `pytest-azurepipelines` to aiohttp test run was reported as "green" while 1 test was failed.
It's super-confusing behavior: https://dev.azure.com/aio-libs/aiohttp/_build/results?buildId=903&view=results

**Comment by asvetlov** [comment]
Sorry, it was my bad
