### ISSUE TITLE
Publish Python 3.8 binary wheels

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/yarl#369]
https://github.com/microsoft/azure-pipelines-image-generation/issues/1317 is a blocker

**Comment by Brekkjern** [comment]
The linked issue has been solved. Is there a chance to publish new wheels soon?

**Comment by asvetlov** [comment]
Multidict should be released first.
Its CI is mostly updated but needs some configuration steps.

**Comment by asvetlov** [comment]
Done in Dec 2019
