### ISSUE TITLE
yarl 1.4.0 does not work with Python versions before 3.7

### ISSUE THREAD

**Issue by Adaephon-GH** [aio-libs/yarl#388]
Hello,

it looks like yarl is no longer compatible with Python 3.5 or 3.6. This comes down to the use of `str.isascii()` in `yarl/__init__.py`:
https://github.com/aio-libs/yarl/blob/54ee226f74f7093a90559fe4bc778d39a8343edc/yarl/__init__.py#L671
As this function was only introduced with Python 3.7, yarl 1.4.0 will not work correctly with previous versions of Python.

# Steps to reproduce:
1. Install yarl 1.4.0 within Python 3.6/3.5 environment
2. Run `python3.6`
3. `import yarl`
4. Call `yarl.URL()` with a hostname (IPs seem to work)

```
Python 3.6.5 (default, May 24 2018, 08:58:10) 
[GCC 8.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from yarl import URL
>>> url = URL('https://www.python.org/~guido?arg=1#frag')
Traceback (most recent call last):
  File "/tmp/foo/yarl/yarl/lib/python3.6/site-packages/yarl/__init__.py", line 667, in _encode_host
    ip = ip_address(ip)
  File "/home/mruf/local/opt/pyenv/versions/3.6.5/lib/python3.6/ipaddress.py", line 54, in ip_address
    address)
ValueError: 'www.python.org' does not appear to be an IPv4 or IPv6 address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/foo/yarl/yarl/lib/python3.6/site-packages/yarl/__init__.py", line 170, in __new__
    val.username, val.password, host, port, encode=True
  File "/tmp/foo/yarl/yarl/lib/python3.6/site-packages/yarl/__init__.py", line 688, in _make_netloc
    ret = cls._encode_host(host)
  File "/tmp/foo/yarl/yarl/lib/python3.6/site-packages/yarl/__init__.py", line 671, in _encode_host
    if host.isascii():
AttributeError: 'str' object has no attribute 'isascii'
>>> 
```

**Comment by webknjaz** [comment]
A possible solution would be falling back to [`curses.ascii.isascii()`].

If somebody wants to give it a try — PRs are welcome!

[`curses.ascii.isascii()`]:
https://docs.python.org/3.5/library/curses.ascii.html#curses.ascii.isascii

**Comment by Adaephon-GH** [comment]
I'll have a go at it. I can think of a few ways to implement that, but I am a bit unsure, which one to choose. It depends quite a bit on how often this line is typically called, especially as the target is to improve performance.

`str.isascii` is quite a bit faster than looping over the string and checking with `curses.ascii.isascii` (or even just `ord(c) <= 127`), even if the very first character is not ASCII. So keeping it for Python 3.7+ would be nice. But checking `hasattr(str, "isascii")` itself takes quite a bit of time and so does `try […] except`. So the question is, is it called often enough that creating a helper method that chooses based on the availability of `str.isascii()` pays of. Or is it called just a few times so that it would not hurt the performance on Python 3.7+ too much, if a more general solution is used.

Either way, the solution for Python 3.6- could look something like this:
```
if all(ord(char)<=127 for char in host):
    return host
```

**Comment by fanjindong** [comment]
Well, a dozen of us spent the whole afternoon troubleshooting this issue.

**Comment by asvetlov** [comment]
Install yarl 1.4.1
