### ISSUE TITLE
Use of `str.isascii` requires python 3.7 or later.

### ISSUE THREAD

**Issue by tomasssalles** [aio-libs/yarl#392]
Commit eda1e050c867c8ea47ddbd8c98d7b3a94c987a1f introduces the use of python 3.7's `str.isascii` method but `setup.py` does not reflect that. The result is:

```
AttributeError: 'str' object has no attribute 'isascii'
```

in applications running python 3.5 or 3.6.

Other than updating the `setup.py` to require python 3.7 for yarl 1.4+, it would also be possible to
replace the code with

```
try:
    host.encode('ascii')
except UnicodeEncodeError:
    pass # Non-ASCII case is handled below.
else:
    return host
```

and keep support for python 3.5 and 3.6.

**Comment by asvetlov** [comment]
Fixed by yarl==1.4.1
