### ISSUE TITLE
Add YARL_NO_EXTENSIONS to README or somewhere in the documentation.

### ISSUE THREAD

**Issue by NazarTopolsky** [aio-libs/yarl#394]
Some popular distros, like Alpine Linux, don't have gcc installed by default. I understand the performance reasoning behind having optimized version as default, but there are valid reasons for not having gcc installed, like image size, so mentioning this environment variable somewhere in documentation as an option is a good idea.

**Comment by asvetlov** [comment]
Would you port https://github.com/aio-libs/multidict/pull/426 to yarl?

**Comment by NazarTopolsky** [comment]
Okay, I'll try to get on this today.
