### ISSUE TITLE
`yarl.URL(...).host` attribute not detected correctly when host is specified by an IP address.

### ISSUE THREAD

**Issue by nawarnoori** [aio-libs/yarl#406]
When passing an `IP` or an `IP:port` combination, `yarl.URL` fails to detect the host correctly:
```python
$ python
Python 3.8.0 (default, Nov 23 2019, 05:36:56) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yarl
>>> yarl.__version__
'1.4.2'
>>> yarl.URL('0.0.0.0').host is None
True
>>> yarl.URL('0.0.0.0:80').host is None
True
>>> 
```
Looking at the code, I think relying on `netloc` for the host in the cases of IP addresses is naive. The correct behaviour here should be to truncate the colon and port part and return just the IP address, e.g.:
```python
>>> yarl.URL('0.0.0.0:80').host
'0.0.0.0'
```
The reason why I'm raising this is right now I have issues with getting `aiohttp` to work with IP addresses (particularly for local development), it fails in `aiohttp.client_reqrep.ClientRequest.update_host`:
```python
    def update_host(self, url: URL) -> None:
        """Update destination host, port and connection type (ssl)."""
        # get host/port
        if not url.host:
            raise InvalidURL(url)  # :(
```

**Comment by asvetlov** [comment]
Please read a comment at the beginning of `yarl.URL` class definition: https://github.com/aio-libs/yarl/blob/master/yarl/__init__.py#L61-L123
It is an extract of RFC 3986.
`yarl.URL('0.0.0.0')` means a relative URL with `path == '0.0.0.0'`.
The same, `yarl.URL('hostname')` means relative URL with `path == 'hostname'`

To make an absolute URL please provide a scheme, the empty scheme is ok too: `yarl.URL("//0.0.0.0").host == '0.0.0.0'`.
