### ISSUE TITLE
Questions about yarl behavior

### ISSUE THREAD

**Issue by xiafu-msft** [aio-libs/yarl#420]
Hi!

We ran into a problem when we were using yarl.
The problem happens on this line https://github.com/aio-libs/yarl/blob/master/yarl/__init__.py#L170
Before L170 was executed `val[2]` was `/container1/%3B.txt`
while after L170 `path` is `/container1/;.txt` 
So it looks like L170 auto-decoded the encoded path.... How can we send out a request without decode the url?

Your help will be appreciated!

**Comment by xiafu-msft** [comment]
Hi! any update on this one

**Comment by webknjaz** [comment]
I don't understand what you're trying to achieve and how you use YARL.

**Comment by xiafu-msft** [comment]
Hi @webknjaz 
Thanks for your reply!
I was trying to send http request to a url which is `xiafuhns.blob.core.windows.net/container1/%3B.txt`
while after this line https://github.com/aio-libs/yarl/blob/master/yarl/__init__.py#L170 was executed my url became `xiafuhns.blob.core.windows.net/container1/;.txt` which is a wrong one....

Feel free to let me know if you need any info! And thanks again to help look into that!

**Comment by webknjaz** [comment]
You're talking about the low level implementation detail, please show your code.

**Comment by AlwxSin** [comment]
Same here. I need to redirect a user to another URL in aiohttp app
`raise web.HTTPFound(location=download_url)` which follows by `self.headers['Location'] = str(URL(location))`
But `yarl` modifies my download URL in unpredict way.
```python
>>> url = 'https://storage.googleapis.com/bucket-name/4badf680bf5%2F0463d893f14%2F6498af44f0%2Fpro%28d%29uction.jpg'
>>> URL(url)
URL('https://storage.googleapis.com/bucket-name/4badf680bf5%2F0463d893f14%2F6498af44f0%2Fpro(d)uction.jpg')
```

My URL contains 4 parts - `{hash1}/{hash2}/{hash3}/{file_name}.{file_ext}`. Note that yarl does not modify encoded slashes, only encoded parentheses.

**Comment by asvetlov** [comment]
Yarl normalizes URL by quoting all not allowed characters *and* unquoting all allowed PCT-encoded sequences.
To disable this please pass `encoded=True` argument to `URL()` constructor or `URL.build()` function.

**Comment by thuan1412** [comment]
Hi @asvetlov , I face the same issue, but in the `update_query`  method. It automatically normalizes the query. Can we disable it in the `update_query` method?

![image](https://user-images.githubusercontent.com/36019052/191479409-acf69858-20d5-4790-9279-3fe23362f1c2.png)
