### ISSUE TITLE
Any reason yarl not allowing bytes in query params?

### ISSUE THREAD

**Issue by mayli** [aio-libs/yarl#425]
As [here](https://github.com/aio-libs/yarl/blob/master/yarl/__init__.py#L892) and [here](https://github.com/aio-libs/yarl/blob/master/yarl/__init__.py#L861).

The API requires sending quoted raw bytes to the endpoint, however aiohttp/yarl doesn't allow it.

**Comment by webknjaz** [comment]
Not sure what you mean. I don't think that using bytes is acceptable.
