### ISSUE TITLE
tmpbuf - compiling error

### ISSUE THREAD

**Issue by pimbolilu** [aio-libs/yarl#43]
Hello,

I get this compiling error:

`sudo pip3 install yarl
Downloading/unpacking yarl
  Downloading yarl-0.8.1.tar.gz (121kB): 121kB downloaded
  Running setup.py (path:/tmp/pip-build-nm8vbb7v/yarl/setup.py) egg_info for package yarl
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            if ch in ALLOWED:
                PyUnicode_WriteChar(ret, ret_idx, ch)
                ret_idx +=1
                continue
    
            tmpbuf = PyUnicode_AsUTF8AndSize(ch, &tmpbuf_size)
                  ^
    ------------------------------------------------------------
    
    yarl/_quoting.pyx:117:15: Assignment to non-lvalue 'tmpbuf'
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-nm8vbb7v/yarl/setup.py", line 27, in <module>
        extensions = cythonize(extensions)
      File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 840, in cythonize
        cythonize_one(*args[1:])
      File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 959, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: yarl/_quoting.pyx
    Compiling yarl/_quoting.pyx because it changed.
    Cythonizing yarl/_quoting.pyx
    Complete output from command python setup.py egg_info:
    

Error compiling Cython file:

------------------------------------------------------------

...

        if ch in ALLOWED:

            PyUnicode_WriteChar(ret, ret_idx, ch)

            ret_idx +=1

            continue

        tmpbuf = PyUnicode_AsUTF8AndSize(ch, &tmpbuf_size)

              ^

------------------------------------------------------------

yarl/_quoting.pyx:117:15: Assignment to non-lvalue 'tmpbuf'

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-nm8vbb7v/yarl/setup.py", line 27, in <module>

    extensions = cythonize(extensions)

  File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 840, in cythonize

    cythonize_one(*args[1:])

  File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 959, in cythonize_one

    raise CompileError(None, pyx_file)

Cython.Compiler.Errors.CompileError: yarl/_quoting.pyx

Compiling yarl/_quoting.pyx because it changed.

Cythonizing yarl/_quoting.pyx

----------------------------------------
`

**Comment by linuxlurak** [comment]
I have exactly the same error and no clue what to do. Im not a total noob but not scripting on a daily basis (neither a weekly ;))

**Comment by linuxlurak** [comment]
Something to note: Problem startet with yarl-0.8.1. No problems before...

**Comment by pimbolilu** [comment]
I also upgraded Cython via pip3 to latest version. But still this problem.

Btw: I am on a raspberry pi in case it has an impact because of arm or so..

**Comment by linuxlurak** [comment]
Im on a raspberry pi too (trying to upgrade home assistant with `pip3 install homeassistant --upgrade` and this depends on yarl-0.8.1...) 
I solved the problem with the following steps:

I cloned the yarl git with: `git clone https://github.com/aio-libs/yarl.git`

Then I changed Line 117 with vim: `vim ./yarl/yarl/_quoting.pyx`. Take nano or vi or whatever you like.
from:
>    cdef char tmpbuf[6]  # place for UTF-8 encoded char plus zero terminator

to:
>    cdef char* tmpbuf  # place for UTF-8 encoded char plus zero terminator

Then installed yarl-0.8.1 manually:
`pip3 install ./yarl/`

**Comment by pimbolilu** [comment]
perfect! It worked also for me, you are my hero of the day :)

Btw: I also needed to update yarl because of the home-assistant upgrade.

**Comment by asvetlov** [comment]
@linuxlurak thanks, I've got your point.
I need to double check the proposed solution -- it may have leak/crash-bug/non-optimal ops.
But my code is buggy obviously.

Will fix it soon.

**Comment by linuxlurak** [comment]
@asvetlov: I am _no_ coder, did no reflections on this change and don't now your code at all :)  So your expertise is in demand :) And thanks for your work!
