### ISSUE TITLE
Can we have `authority`?

### ISSUE THREAD

**Issue by dimaqq** [aio-libs/yarl#430]
RFC3986 defines `authority`, while yarl.URL it seems only offers `.host`, `.port`, etc.

For comparison, `urllib.parse.ParseResult` has a `.netloc` field.
(which includes credentials, like `user@host.com:8080`, which are not part of authority as far as I can tell, but I'm lost in RFC, I really can't tell 🤷‍♂️).

Would it be a good idea to have an `authority` property which which matches that?
It would be quite useful for HTTP/2 where the pseudo-headers are send instead of a full URL:
* scheme (yarl has it)
* path (yarl has `path_qs`)
* method (out of scope)
* authority (yarl users have to combine it using `host` and `explicit_port`)

There's a precedent for this: yarl offers `path_qs` which is a combination of `path` and `query`.

**Comment by asvetlov** [comment]
I think this is a good idea. An excerption from RFC 3986
```
authority   = [ userinfo "@" ] host [ ":" port ]
```
