### ISSUE TITLE
improve addition of query string

### ISSUE THREAD

**Issue by vanyakosmos** [aio-libs/yarl#434]
Right now we can append url parts like this:
```python
base = URL('https://example.com')
url = base / 'foo' / 'bar'
```
It would be cool to be able to add query string in the similar way:
```python
base = URL('https://example.com')
url = base / 'foo' // {'param': 'bar'}
```

Alternative operators: `&`, `%`

**Comment by webknjaz** [comment]
Do you have any example of a library that does this? I'm not sure about the UX implications here.
For example, I'd expect an API to be more like
```python
proto = proto('https')
url = proto // 'example.com' / 'foo' & {'param': 'bar'} & {'param2': 'boo'}
```

**Comment by vanyakosmos** [comment]
> Do you have any example of a library that does this?

Do you mean libs that use `//`? No. 

I was thinking about another operators as well:
- `//` looks to similar to `/` and can be misunderstood (as some kind of fancy path extension or literal double slash in URL, eg `example.com/foo//bar`)
- `&` is associated with addition and set intersection. It can be used in the future to somehow merge urls or to find common parts: `'example.com/foo/1' & 'example.com/foo/bar/baz' == 'example.com/foo/'`
- `%` is rarely used and it looks somewhat similar to `?`. That's why I used `%` in PR #435.
