### ISSUE TITLE
Misleading TypeError

### ISSUE THREAD

**Issue by Lonami** [aio-libs/yarl#444]
This error claims only `(str, str)` pairs are allowed:
https://github.com/aio-libs/yarl/blob/9afd40d7b43b1af43c4f27850b64225d238b97cd/yarl/__init__.py#L900-L903

However, judging from the code, one may actually use `(str, int)` just fine:
https://github.com/aio-libs/yarl/blob/9afd40d7b43b1af43c4f27850b64225d238b97cd/yarl/__init__.py#L894-L898
https://github.com/aio-libs/yarl/blob/9afd40d7b43b1af43c4f27850b64225d238b97cd/yarl/__init__.py#L855-L860

**Comment by asvetlov** [comment]
Fixed by 8ef1f14
