### ISSUE TITLE
params do not encode right

### ISSUE THREAD

**Issue by fuchaoqun** [aio-libs/yarl#45]
Test Code:

from yarl import URL
url = URL('https://github.com')
print(url.with_query({'a':'b','c':'%2'}))

Output:

https://github.com/?a=b&c=

%2 does not encode right

**Comment by asvetlov** [comment]
Thank for report

**Comment by tangyouze** [comment]
here's some other test cases not working correct


```
import yarl

print(yarl.__version__)
url = yarl.URL('https://github.com')
print(url.with_query({'a': 'b', 'c': ';2'}))

url = yarl.URL('https://github.com/query?q=%3bx')
print(url.query)
```

output
```
https://github.com/?a=b&c=;2
<MultiDictProxy('q': '', 'x': '')>
```

**Comment by fafhrd91** [comment]
should be fixed in master

**Comment by munkkipossu** [comment]
The print command was left in (on line 692). Was this intentional?

**Comment by LLFourn** [comment]
Obviously not intentional. @fafhrd91 plz fix!

**Comment by fafhrd91** [comment]
oh
