### ISSUE TITLE
Is it possible to not treat semicolons as query delimiter?

### ISSUE THREAD

**Issue by playpauseandstop** [aio-libs/yarl#473]
I'm using `yarl.URL` to work with Google Fonts URL such as,

```
https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;1,100&display=swap
```

And it results in unexpected (from my POV) query value,

```python
from yarl import URL
url = URL("https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;1,100&display=swap")
assert url.query["family"] == "Roboto:ital,wght@0,100"
```

While, I expect value of `url.query["family"]` will equal to `"Roboto:ital,wght@0,100;1,100"`.

As my expectation is valid, while working with [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) in browser, I wonder whether it possible to tell `yarl.URL` to not treat semicolon as query delimiter? Or only possibility is to "decode" semicolon to `%3B` before passing URL value to `yarl.URL`? (as done in https://github.com/aio-libs/yarl/blob/master/tests/test_url_query.py#L70-L73)

----

BTW, next JavaScript code will return proper `family` search param,

```js
const url = new URL("https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;1,100&display=swap");
url.searchParams.get("family") == "Roboto:ital,wght@0,100;1,100";
```

----

Same, while using [url](https://crates.io/crates/url) crate in rust,

```rust
let url = Url::parse(
    "https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;1,100&display=swap",
)
.unwrap();

let mut pairs = url.query_pairs();
assert_eq!(pairs.count(), 2);

assert_eq!(
    pairs.next(),
    Some((
        Cow::Borrowed("family"),
        Cow::Borrowed("Roboto:ital,wght@0,100;1,100")
    ))
);
```

The code above, will compile properly and parsed `url` will have `family` query pair of expected value.

**Comment by webknjaz** [comment]
The behavior is correct as far as backward compat with older RFCs go. Also, AFAIR this behavior comes from stdlib's urllib that implements the older standard with the recommendation for supporting `;` as a delimiter for implementations that may rely on it (mostly old CGI IIRC).

**Comment by webknjaz** [comment]
I've posted a related explanation here: https://github.com/cherrypy/cherrypy/issues/1860#issuecomment-640246780.

**Comment by webknjaz** [comment]
Seealso: https://github.com/cherrypy/cherrypy/issues/1860#issuecomment-640217027

**Comment by playpauseandstop** [comment]
Hi @webknjaz,

Thanks for your answer, I expected it (_unfortunately_), as I acknowledged with standard library `parse_qs` behaviour. 

In that case, I'm closing the issue as `wontfix`, but leaving the workaround (ugly one) for someone, who will hit the same issue after me,

```py
from yarl import URL


def with_query_string(url: URL, next_query_string: str) -> URL:
    """Entirely replace URL query string.

    Such as ``url.with_query(...)`` method, but for query string.
    """
    return URL.build(
        scheme=url.scheme,
        user=url.user,
        password=url.password,
        host=url.host or "",
        port=url.port,
        path=url.path,
        query_string=next_query_string,
        fragment=url.fragment,
    )


def fix_url_with_semicolons(url: URL) -> URL:
    """Fix URL, when its query string contains semicolons.

     This will keep semicolons as part of query value, instead of treat it as
     delimiter, as done by default.
     """
    if ";" in url.query_string:
        return with_query_string(url, url.query_string.replace(";", "%3B"))
    return url


url = URL("https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;1,100&display=swap")
assert url.query["family"] == "Roboto:ital,wght@0,100"

fixed_url = fix_url_with_semicolons(url)
assert fixed_url.query["family"] == "Roboto:ital,wght@0,100;1,100"
```

**Comment by webknjaz** [comment]
FWIW I want to emphasize that things like this are often subjects to a contract between the specific client and server pair, one level higher than HTTP. And, as a library, YARL has no way of knowing whether the developer means `;` as a delimiter. The best way to tell your intent to YARL is really by escaping any characters that may have special meaning within the given set of parsers, just like you would do with `&`.

**Comment by playpauseandstop** [comment]
Re,

> I want to emphasize that things like this are often subjects to a contract between the specific client and server pair

> And, as a library, YARL has no way of knowing whether the developer means `;` as a delimiter

To be short, there is a [WHATWG URL Standard](https://url.spec.whatwg.org) specification and `yarl` (as well as standard Python `parse_qs` function) do not aware of it. 

In same time JavaScript (via [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) object) and Rust (via [url](https://crates.io/crates/url) crate) implement given specification and provide standard way of parsing query strings by using only `&` as delimiter.

> [5.1. application/x-www-form-urlencoded parsing](https://url.spec.whatwg.org/#urlencoded-parsing)
> 
> The application/x-www-form-urlencoded parser takes a byte sequence input, and then runs these steps:
> 
> 1. Let sequences be the result of splitting input on 0x26 (&).

We can spend more time discussing on a topic, but the result will be the same: `yarl` will treat `;` as a query delimiter, while URL Standard implementations will not.

----

And here the implementation details of query string parsing,

- In JavaScript, [whatwg-url](https://github.com/jsdom/whatwg-url) library, [URLSearchParams constructor](https://github.com/jsdom/whatwg-url/blob/ecca76a8b0d4073d8c2f5b249609018bba6ee9b2/src/URLSearchParams-impl.js#L29) -> [parseUrlencoded function](https://github.com/jsdom/whatwg-url/blob/ecca76a8b0d4073d8c2f5b249609018bba6ee9b2/src/urlencoded.js#L11)
- In rust, url crate, [Url.query_pairs method](https://github.com/servo/rust-url/blob/55395ed3099b26a58a82f6fef09e609d52b674b3/src/lib.rs#L1156) + [form_urlencoded::parse function](https://github.com/servo/rust-url/blob/master/form_urlencoded/src/lib.rs#L54)

**Comment by webknjaz** [comment]
Neither WHATWG nor W3C influence how HTTP works: it's defined by RFCs. WHATWG/W3C show us one of the ways of writing high-level applications not top of HTTP which by itself is lower level. YARL is used in HTTP frameworks and thus it must follow RFCs, because higher-level users may interpret things according to their app needs while HTTP-level interactions should remain intact.
