### ISSUE TITLE
Yank 1.5.0 in PyPI

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/yarl#490]
@asvetlov plz go to PyPI and click "Yank" (not delete!) next to release 1.5.0 so that it shows up as unrecommended. I don't have enough power over there.

**Comment by asvetlov** [comment]
Yanked.
User `webknjaz` is added to PyPI project as co-owner

**Comment by webknjaz** [comment]
Thanks!

**Comment by webknjaz** [comment]
Weird, I don't see any of that. Are you sure you clicked confirm?

**Comment by webknjaz** [comment]
I can see it among my projects so I guess there's just some catching issue there. Closing for now.
