### ISSUE TITLE
yarl.URL.raw_query_string is not raw

### ISSUE THREAD

**Issue by helmutg** [aio-libs/yarl#498]
Consider the following code:
    >>> import yarl
    >>> yarl.URL("/?x=!%21").raw_query_string
    'x=!!'

I would have expected the output `'x=!%21'`. For a the `query_string` member, the given output seems sensible, but not for `raw_query_string`. This happens to break the `aiohttp-wsgi` package via the `aiohttp` package. In the end, the `QUERY_STRING` in the `environ` dict happens to be percent-unescaped, but WSGI expects it to be escaped. This is a real bug in `aiohttp-wsgi`. Can it be fixed at the `yarl` layer by making `raw_query_string` return a raw query string?

**Comment by serhiy-storchaka** [comment]
It is not only `raw_query_string`, it is the same for all `raw_*` attributes:
```
>>> URL("/!%21").raw_path
'/!!'
```
In what way it breaks the `aiohttp-wsgi` package? Could you please provide more details?

**Comment by helmutg** [comment]
The `aiohttp-wsgi` package uses the `yarl.URL` to reconstruct a number of WSGI parameters including `QUERY_STRING`. If you use a digest authentication middleware on top of that, it has to reconstruct the original URL from the `QUERY_STRING` and a few other fields and match it against the one included in the `Authentication` header. With the current `yarl` behaviour, any request that happens to contain `%21` (i.e. an escaped exclamation mark) fails this check. As a result digest authentication fails.

Do note that it is impossible to reconstruct the original URL from the `raw_*` attributes at present. You cannot tell whether a `!` originally was a `!` or a `%21`. Therefore, this issue affects any possible digest authentication middleware no matter how it is implemented. If this is not fixed in `yarl`, then `aiohttp` needs to stop using `yarl` and resort to more bare bones mechanisms.

**Comment by helmutg** [comment]
I've attempted fixing this in `yarl` and just even introducing this behaviour change is going to break a lot. The tests become very unhappy. While I expected `yarl.URL` to be able to fully recover the given string, that seems to be a non-goal judging from the tests. And while the `raw_*` members look like raw, their intention really seems to be to represent the quoted form (e.g. when dealing with non-ascii utf8 characters). Given the number of tests broken by the proposed change, I don't think it is acceptable in any way.

If you follow this far, `aiohttp-wsgi` must not use `yarl`, because it must allow a faithful reconstruction of the URL and that happens to be a non-goal for `yarl`. Quite simply, `yarl` does not solve the URL parsing needs that `aiohttp-wsgi` has. I'll look into opening an issue there parse using something else.

**Comment by asvetlov** [comment]
Use `encoded=True` argument if you pass already raw string:
```
>>> import yarl
>>> yarl.URL("/?x=!%21", encoded=True).raw_query_string
'x=!%21'
```

**Comment by helmutg** [comment]
Thank you. That helped a lot. Indeed the `encoded=True` argument has been added to `aiohttp`, which should fix the reported issue. See https://github.com/aio-libs/aiohttp/commit/f2afa2f054ba9e6c5d142e00233f0073925e7893
