### ISSUE TITLE
Wheel support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [aio-libs/yarl#507]
**Summary**
Installing yarl on aarch64 via pip using command "pip3 install yarl" tries to build wheel from source code.

**Problem description**
yarl doesn't have wheel for aarch64 on PyPI repository. So, while installing yarl via pip on aarch64, pip builds wheel for same resulting in it takes more time to install yarl. Making wheel available for aarch64 will benefit aarch64 users by minimizing yarl installation time.

**Expected Output**
Pip should be able to download yarl wheel from PyPI repository rather than building it from source code.

@yarl-taem, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make yarl wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by webknjaz** [comment]
Once it's implemented in the shared pipelines repo, it can be reused.

Ref: https://github.com/aio-libs/multidict/pull/519#pullrequestreview-495544375

**Comment by mattsplats** [comment]
@asvetlov Per the changes you made to multidict: https://github.com/aio-libs/multidict/issues/500

I was going to see about adding aarch64 via Azure pipelines after this change: https://github.com/aio-libs/azure-pipelines/pull/1

I won't bother if you're planning on using Github Actions here as well.

**Comment by asvetlov** [comment]
I think github workflows are the better solution now.
It has the same runner as azure (a fork of azure's version actually) but provides better syntax and infrastructure.
I'm thinking about extracting common parts into a custom aio-lib action(s); but for the start, I can live with a copy-paste solution until I'll be too boring with maintaining these scattered configuration files.

**Comment by asvetlov** [comment]
yarl 1.6.1 is out.
I'll convert `frozenlist` and `aiosignals` first and return to aiohttp 3.7 release (with Python 3.9, aarch64 and others) after it.

**Comment by asvetlov** [comment]
Done by yarl 1.6.1 release
