### ISSUE TITLE
Support python 3.3 by including pathlib in the requirements

### ISSUE THREAD

**Issue by LaurensBosscher** [aio-libs/yarl#52]
Hi,

Installing Yarl in Python 3.3 fails because pathlib is only included in the stdlib since 3.4: https://docs.python.org/3.4/library/pathlib.html

I saw that Python 3.3 is not included in the supported version but since pathlib is available on pypi it seems that it would be possible to support Python 3.3, at least until it is EOL (September 2017).

**Comment by fafhrd91** [comment]
Could you provide PR?

**Comment by asvetlov** [comment]
What is your use case?
aiohttp itself doesn't support Python 3.3
I really doubt if many people use 3.3 now.
*Official* python 3.3 support requires publishing binary wheels on PyPI as well -- don't want to do it.

I suspect running `pip install pathlib` could satisfy all your needs without `yarl` change.
