### ISSUE TITLE
need create prebuilt wheels for python 3.9

### ISSUE THREAD

**Issue by SaidBySolo** [aio-libs/yarl#526]
🐣 **Is your feature request related to a problem? Please describe.**

If there is no wheel for 3.9.0, the Windows user must get the c++ build tool

💡 **Describe the solution you'd like**

I wish we had a prebuilted wheel

❓ **Describe alternatives you've considered**

Use Linux

📋 **Additional context**

Thank you for your time :)

**Comment by webknjaz** [comment]
This is blocked on Azure rolling out images with support for CPython 3.9: https://github.com/aio-libs/multidict/issues/534#issuecomment-704928736

**Comment by asvetlov** [comment]
Done by yarl 1.6.1 release
