### ISSUE TITLE
Yarl 1.6.1 failed building wheel

### ISSUE THREAD

**Issue by haroldhues** [aio-libs/yarl#530]
🐞 **Describe the bug**

After yarl 1.6.1 was released our CI build started to fail to install yarl because `Failed building wheel for yarl`; `gcc` in turn failed because of a missing? file `gcc: error: yarl/_quoting_c.c: No such file or directory`

💡 **To Reproduce**

Build the following docker file:

```docker
FROM jupyter/scipy-notebook:66c99628f4b8

RUN echo "aiohttp==3.6.2" > /opt/conda/lib/python3.7/site-packages/requirements.prod.txt
RUN python3 -m pip install --no-cache-dir -r /opt/conda/lib/python3.7/site-packages/requirements.prod.txt
```

💡 **Expected behavior**

Yarl is installed

📋 **Logs/tracebacks**

Here is the output from pip install:
```
Step 3/3 : RUN python3 -m pip install --no-cache-dir -r /opt/conda/lib/python3.7/site-packages/requirements.prod.txt
 ---> Running in 954ede6b1b98
Collecting aiohttp==3.6.2 (from -r /opt/conda/lib/python3.7/site-packages/requirements.prod.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/e3/71/6000eacb8923d9fd07aa8784a8fab4f022ae697f3c2456d7dca75c743dd6/aiohttp-3.6.2-cp37-cp37m-manylinux1_x86_64.whl (1.2MB)
Requirement already satisfied: chardet<4.0,>=2.0 in /opt/conda/lib/python3.7/site-packages (from aiohttp==3.6.2->-r /opt/conda/lib/python3.7/site-packages/requirements.prod.txt (line 1)) (3.0.4)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.7/site-packages (from aiohttp==3.6.2->-r /opt/conda/lib/python3.7/site-packages/requirements.prod.txt (line 1)) (19.1.0)
Collecting multidict<5.0,>=4.5 (from aiohttp==3.6.2->-r /opt/conda/lib/python3.7/site-packages/requirements.prod.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/85/b8/a9fe777dab4c6aa067b516a34fe995213707e490ea1e72f823949a830a6a/multidict-4.7.6-cp37-cp37m-manylinux1_x86_64.whl (149kB)
Collecting async-timeout<4.0,>=3.0 (from aiohttp==3.6.2->-r /opt/conda/lib/python3.7/site-packages/requirements.prod.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/e1/1e/5a4441be21b0726c4464f3f23c8b19628372f606755a9d2e46c187e65ec4/async_timeout-3.0.1-py3-none-any.whl
Collecting yarl<2.0,>=1.0 (from aiohttp==3.6.2->-r /opt/conda/lib/python3.7/site-packages/requirements.prod.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/d7/16/de7f1a8bee0abe00478bef64c217ad2656b9b33a483e8e0b980250e2a850/yarl-1.6.1.tar.gz (116kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Requirement already satisfied: idna>=2.0 in /opt/conda/lib/python3.7/site-packages (from yarl<2.0,>=1.0->aiohttp==3.6.2->-r /opt/conda/lib/python3.7/site-packages/requirements.prod.txt (line 1)) (2.8)
Collecting typing-extensions>=3.7.4; python_version < "3.8" (from yarl<2.0,>=1.0->aiohttp==3.6.2->-r /opt/conda/lib/python3.7/site-packages/requirements.prod.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/60/7a/e881b5abb54db0e6e671ab088d079c57ce54e8a01a3ca443f561ccadb37e/typing_extensions-3.7.4.3-py3-none-any.whl
Building wheels for collected packages: yarl
  Building wheel for yarl (PEP 517): started
  Building wheel for yarl (PEP 517): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /opt/conda/bin/python3 /opt/conda/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpi4r33xjh
       cwd: /tmp/pip-install-kxqtnjde/yarl
  Complete output (39 lines):
  **********************
  * Accellerated build *
  **********************
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/yarl
  copying yarl/_quoting_py.py -> build/lib.linux-x86_64-3.7/yarl
  copying yarl/_url.py -> build/lib.linux-x86_64-3.7/yarl
  copying yarl/__init__.py -> build/lib.linux-x86_64-3.7/yarl
  copying yarl/_quoting.py -> build/lib.linux-x86_64-3.7/yarl
  running egg_info
  writing yarl.egg-info/PKG-INFO
  writing dependency_links to yarl.egg-info/dependency_links.txt
  writing requirements to yarl.egg-info/requires.txt
  writing top-level names to yarl.egg-info/top_level.txt
  reading manifest file 'yarl.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.cache' found anywhere in distribution
  warning: no files found matching 'yarl/_quoting_c.c'
  warning: no previously-included files found matching 'yarl/*.html'
  warning: no previously-included files found matching 'yarl/*.so'
  warning: no previously-included files found matching 'yarl/*.pyd'
  no previously-included directories found matching 'docs/_build'
  writing manifest file 'yarl.egg-info/SOURCES.txt'
  copying yarl/__init__.pyi -> build/lib.linux-x86_64-3.7/yarl
  copying yarl/_quoting_c.pyi -> build/lib.linux-x86_64-3.7/yarl
  copying yarl/_quoting_c.pyx -> build/lib.linux-x86_64-3.7/yarl
  copying yarl/py.typed -> build/lib.linux-x86_64-3.7/yarl
  running build_ext
  building 'yarl._quoting_c' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/yarl
  gcc -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/conda/include/python3.7m -c yarl/_quoting_c.c -o build/temp.linux-x86_64-3.7/yarl/_quoting_c.o
  gcc: error: yarl/_quoting_c.c: No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for yarl
  Running setup.py clean for yarl
Failed to build yarl
ERROR: Could not build wheels for yarl which use PEP 517 and cannot be installed directly
The command '/bin/sh -c python3 -m pip install --no-cache-dir -r /opt/conda/lib/python3.7/site-packages/requirements.prod.txt' returned a non-zero code: 1
```

📋 **Your version of the Python**

```console
$ python --version
Python 3.7.3
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

Not applicable, trying to install `aiohttp==3.6.2`

📋 **Additional context**

**Comment by haroldhues** [comment]
@asvetlov It looks like the way releases are created was revamped - is it possible that the new way is accidentally dropping files (namely `_quoting_c`)?

**Comment by lun-4** [comment]
Got the same CI error on a different project with Python 3.8, Installing `aiohttp==3.6.3` [fixes the issue](https://github.com/aio-libs/aiohttp/commit/2d36ef6911a1d49001381da40d658a70d64168fa).

**Comment by jamest-spring** [comment]
I can confirm that yarl 1.6.1 sdist does not contain `yarl/_quoting_c.c`: 
```
» tar -ztf yarl-1.6.1.tar.gz | grep -i _quoting.c
yarl-1.6.1/yarl/_quoting_c.pyi
yarl-1.6.1/yarl/_quoting_c.pyx
```

while 1.6.0 sdist does contain `yarl/_quoting_c.c`:
```
» tar -ztf yarl-1.6.0.tar.gz  | grep -i _quoting.c
yarl-1.6.0/yarl/_quoting_c.c
yarl-1.6.0/yarl/_quoting_c.pyi
yarl-1.6.0/yarl/_quoting_c.pyx
```

**Comment by espears1** [comment]
I can confirm the same error for Python 3.6.8 (transitive install from aiohttp requirements).

**Comment by asvetlov** [comment]
You are right.
Thanks for the report.
I'll fix it ASAP

**Comment by asvetlov** [comment]
Fixed by yarl 1.6.2

**Comment by v1a0** [comment]
In my case it was a problem to install "aiohttp==3.7.4.post0".

```bash
python3.9 -m pip install aiohttp==3.7.4.post0
```

> warning: the 'license_file' option is deprecated, use 'license_files' instead
  adding license file 'LICENSE' (matched pattern 'LICENSE')
  reading manifest file 'yarl.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.cache' found anywhere in distribution
  warning: no previously-included files found matching 'yarl/*.html'
  warning: no previously-included files found matching 'yarl/*.so'
  warning: no previously-included files found matching 'yarl/*.pyd'
  no previously-included directories found matching 'docs/_build'
  writing manifest file 'yarl.egg-info/SOURCES.txt'
  copying yarl/init.pyi -> build/lib.linux-armv7l-3.9/yarl
  copying yarl/_quoting_c.c -> build/lib.linux-armv7l-3.9/yarl
  copying yarl/_quoting_c.pyi -> build/lib.linux-armv7l-3.9/yarl
  copying yarl/_quoting_c.pyx -> build/lib.linux-armv7l-3.9/yarl
  copying yarl/py.typed -> build/lib.linux-armv7l-3.9/yarl
  running build_ext
  building 'yarl._quoting_c' extension
  creating build/temp.linux-armv7l-3.9
  creating build/temp.linux-armv7l-3.9/yarl
  arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.9 -c yarl/_quoting_c.c -o build/temp.linux-armv7l-3.9/yarl/_quoting_c.o
  yarl/_quoting_c.c:4:10: fatal error: Python.h: No such file or directory
      4 | #include "Python.h"
        |          ^~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1
    ----------------------------------------
  ERROR: Failed building wheel for yarl
  Failed to build multidict yarl
  ERROR: Could not build wheels for multidict, yarl which use PEP 517 and cannot be installed directly


Fix it by install python dev tools: 
```bach
apt install python3.9-dev
```

## MAKE SURE YOU INSTALL IT FOR RIGHT PYTHON VERSION! (`python3.x-dev`)
### If you use python 3.x install `python3.x-dev`, and so on

**Comment by webknjaz** [comment]
@v1a0 your problem is in no way related to this issue.
