### ISSUE TITLE
win32 wheels are dropped since 1.6.1

### ISSUE THREAD

**Issue by jiasli** [aio-libs/yarl#535]
🐞 **Describe the bug**

Per the [PyPI page](https://pypi.org/project/yarl/#files), `win32` wheels are dropped since `1.6.1`. [`1.6.0`](https://pypi.org/project/yarl/1.6.0/#files) still has those wheels like `yarl-1.6.0-cp36-cp36m-win32.whl`.

Our CI which uses a 32-bit embeddable Python fails (https://github.com/Azure/azure-cli/pull/15508), because it 

1. fails to download a `win32` wheel
2. fails to build from source `yarl-1.6.2.tar.gz` due to the absence of `Python.h` from the embeddable Python

💡 **Expected behavior**

`win32` wheels should be released as before.

📋 **Additional context**

The same also happens for `multidict`.

**Comment by webknjaz** [comment]
To implement this, you'd need to parametrize https://github.com/aio-libs/yarl/blob/8b6367c/.github/workflows/ci.yml#L236-L238. PRs are welcome.

**Comment by asvetlov** [comment]
I'll fix the build setup and publish a bugfix release for all affected libraries
