### ISSUE TITLE
Fail test_semicolon_as_separator  with Python 3.9.2 and Python 3.8.8

### ISSUE THREAD

**Issue by shadchin** [aio-libs/yarl#563]
🐞 **Describe the bug**
Because of new behavior of parse_qsl, test_semicolon_as_separator began to fall - https://bugs.python.org/issue42967

📋 **Logs/tracebacks**
```python-traceback (paste your traceback in the next line)
    def test_semicolon_as_separator():
        u = URL("http://127.0.0.1/?a=1;b=2")
>       assert len(u.query) == 2
E       assert 1 == 2
E         +1
E         -2
```

📋 **Your version of the Python**

```console
$ python --version
Python 3.9.2
```

**Comment by sandrotosi** [comment]
Hey there! I just want to let you know that, due to this bug, a bug chunk of the AIO libraries in debian are in danger of being removed from the "very nearly almost quite there" release; the likes of httpx, fastapi, etc

it'd be great if you could have a look at this with a certain urgency :)

thanks already!

**Comment by webknjaz** [comment]
Somebody needs to send a PR then.

**Comment by shadchin** [comment]
I have fix - https://github.com/shadchin/yarl/commit/8816bbc7b1e66c8c167578f1f93692de76f0a71b
but my english bad, I can't describe this change in the documentation

**Comment by webknjaz** [comment]
That can be sorted during code review. Also, that patch needs to be improved to ensure consistency across the supported Python versions.

**Comment by sandrotosi** [comment]
> that patch needs to be improved to ensure consistency across the supported Python versions.

is there something more than https://github.com/shadchin/yarl/commit/8816bbc7b1e66c8c167578f1f93692de76f0a71b#diff-657d7257a2bac78ab69f50e60aa9cef5620adc8cd7f902d4e4cbeb0c6e78a434R555-R558 that needs to be done? i think if you're explicit in what changes you want to see, @shadchin can then easily follow up

thanks!

**Comment by webknjaz** [comment]
I'd rather comment on PR rather than attempting to point to correct lines in an issue comment. But yes, I don't like that this adds the feature that only works depending on the runtime. It should work always, regardless of the runtime, if it's configurable.

**Comment by asvetlov** [comment]
Fixed
