### ISSUE TITLE
Azure build ci pipline status badge not showing up in the docs

### ISSUE THREAD

**Issue by ppecheux** [aio-libs/yarl#569]
🐞 **Describe the bug**
azure build ci pipeline status badge not showing up in the docs. It is displaying the link to azure pipelines

💡 **To Reproduce**
watch the badge under the code coverage badge on this page https://yarl.readthedocs.io/en/latest/
(currently, when I go to this link https://dev.azure.com/aio-libs/yarl/_apis/build/status/CI?branchName=master, it says the "Build pipeline CI was not found.")

💡 **Expected behavior**
display a status badge (or display nothing ?)

**Comment by webknjaz** [comment]
Feel free to send a PR removing the badge. This repo is fully migrated to GHA.
