### ISSUE TITLE
Support requests for * in request URIs (OPTIONS *)

### ISSUE THREAD

**Issue by jschlyter** [aio-libs/yarl#593]
It seems to me it is not currently possible to construct a URL that results in a request for `*`, e.g. requests for `OPTIONS *`. I'd be happy to provide code with some guidance. Setting the `path` element to `None` or `*` would be option, but perhaps there is an easier way?

xref: https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.7

**Comment by webknjaz** [comment]
I don't think `*` is a valid URL. https://datatracker.ietf.org/doc/html/rfc7230#section-5.3.4 only seems to exist in the context of HTTP requests but not generic URLs. So maybe such change doesn't belong in YARL but rather aiohttp / HTTP parser.

**Comment by jschlyter** [comment]
I agree.
