### ISSUE TITLE
Add `with_suffix()` method

### ISSUE THREAD

**Issue by michaelaye** [aio-libs/yarl#613]
### Is your feature request related to a problem?

I love how yarl follows the pathlib.Path syntax, so was a bit disappointed to not have a `with_suffix()` method when I needed it. Could it be added?

### Describe the solution you'd like

Similar to pathlib, `with_suffix()` should take a URL to a file, like:

url = yarl.URL("https://a.b.com/index.html")

and change it to:

url.with_suffix(".md")

-> https://a.b.com/index.md

### Describe alternatives you've considered

`with_name()` works as a workaround, but it's sometimes cumbersome to fish out the name first, and do string ops on it before adding it back to the URL.

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by asvetlov** [comment]
The request makes sense.
Please feel free to prepare a patch.
I would say that `.suffix` attribute should be supported if `.with_suffix()` is added.
