### ISSUE TITLE
Yarl 1.7.1 missing from pypi.

### ISSUE THREAD

**Issue by jameshilliard** [aio-libs/yarl#633]
### Describe the bug

I noticed that the latest yarl release on github is version `1.7.1` but pypi only seems to have `1.7.0` [here](https://pypi.org/project/yarl/).

**Comment by asvetlov** [comment]
Both versions have the same content actually; this is a result of a build process bug.
Maybe 1.7.2 is needed to sync everything but I'm overwhelmed by more important bug fixes, sorry.

**Comment by asvetlov** [comment]
FYI, yarl 1.7.2 was released for https://github.com/aio-libs/yarl/issues/623 bugfix
