### ISSUE TITLE
Allow integers in qs

### ISSUE THREAD

**Issue by imbolc** [aio-libs/yarl#65]
I think it's very common case, e.g. `url.update_query(page=1)` and it looks harmless.

**Comment by fafhrd91** [comment]
I think it is reasonable

@asvetlov ?

**Comment by AraHaan** [comment]
Let me see if I can do something about this.

**Comment by asvetlov** [comment]
The issue was raised many times but I strongly disagree with proposal.
It's handy but breaks the rule: everything is strings only.
If we will allow integers how to do with floats and bools?

Anyway it saves just five symbols: instead of `1` you should type `str(1)`. 
Not very hard work!
