### ISSUE TITLE
Ship Python 3.6 wheels.

### ISSUE THREAD

**Issue by AraHaan** [aio-libs/yarl#67]
Without python 3.6 wheels I cannot do the things as explained here: https://github.com/aio-libs/multidict/issues/59

Please fix so I can pip install on python 3.6 and so I can move my code out of just 3.5 now because of the weels that are missing for 3.6.

**Comment by AraHaan** [comment]
Part 1/2 of this is merged. for multidict and this library. When the travis parts are merged I will close this PR.

**Comment by AraHaan** [comment]
Now all I have to do is wait for an pushed copy of the wheels for 3.6 on pypi to get uploaded.

**Comment by fafhrd91** [comment]
should be fixed

**Comment by AraHaan** [comment]
Thanks
