### ISSUE TITLE
v1.8 failed to release

### ISSUE THREAD

**Issue by mjpieters** [aio-libs/yarl#698]
### Describe the bug

The [1.8 tag exists](https://github.com/aio-libs/yarl/releases/tag/v1.8.0), but the [release step failed](https://github.com/aio-libs/yarl/runs/5186918297?check_suite_focus=true):

```
Traceback (most recent call last):
  File "/get_releasenote.py", line 256, in <module>
    sys.exit(main())
  File "/get_releasenote.py", line 229, in main
    ctx.version = find_version(
  File "/get_releasenote.py", line 206, in find_version
    raise ValueError(f"Unable to determine version in file '{version_file}'")
ValueError: Unable to determine version in file 'yarl/__init__.py'
```

As a result, the most recent version on PyPI is still 1.7.2, which doesn't have the new `.suffix` support. The *stable* tagged RTD documentation [does include `URL.suffix`](https://yarl.readthedocs.io/en/stable/api.html#yarl.URL.suffix), which caused me some confusion.

I'd love to have exactly that feature for a project I'm contributing to, can the release be pushed out, even if only manually?

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.7.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /Users/mj/Library/Caches/pypoetry/virtualenvs/nitpick-ImfW6xDq-py3.7/lib/python3.7/site-packages
Requires: idna, multidict, typing-extensions
Required-by:
```

### OS

macOS

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by mjpieters** [comment]
It looks like a [potential fix](https://github.com/aio-libs/create-release/pull/2) is in the works.

@asvetlov what’s the status there? Anything I can do that would unblock this?

**Comment by asvetlov** [comment]
Heh.
Could you help with `get_releasenote.py` fixing?
Sorry, I'm spending my spare time on CPython/asyncio improvements.
Python 3.11 feature freeze is in a month.

**Comment by mjpieters** [comment]
> Could you help with get_releasenote.py fixing?

I'll see what I can do. At first glance your regex can't work (`\[number]` references don't work inside character classes), that's probably the root cause.

**Comment by mjpieters** [comment]
Apart from the get-releasenote issue, there is another: the 1.8 tag doesn't actually contain a 1.8 version string. We'll need to remedy that first!

What is the proper release process here?

- Update the version string
- Move the 1.8 tag, or, if that's preferred instead, tag 1.8.1.

Anything else?

**Comment by webknjaz** [comment]
I'm going to close this because the action items mentioned here are mostly complete, please read further investigation and steps @ https://github.com/aio-libs/yarl/issues/706#issuecomment-1200509764.
