### ISSUE TITLE
CPython 3.11 wheels on PyPI

### ISSUE THREAD

**Issue by altendky** [aio-libs/yarl#781]
### Is your feature request related to a problem?

Just helping bump other projects on 3.11 support as I try to add it to my own.

### Describe the solution you'd like

CPython 3.11 wheels available on PyPI.

### Describe alternatives you've considered

Presently our CI is building the wheels from the sdist on PyPI but this doesn't work well for all users that don't have development tools installed.

### Additional context

Thanks!

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by webknjaz** [comment]
I was planning to do this for yarl+multidict+aiohttp on Oct 24, once it's final.

**Comment by Senpos** [comment]
Hi @webknjaz!
Sorry for the ping, but I just wanted to let you know that the final version of CPython 3.11 has been released, please, consider building wheels. 🙏 Thanks! <3

**Comment by webknjaz** [comment]
Yep, I remember. It's still in my backlog.

**Comment by AmirHmZz** [comment]
Any updates on this ?

**Comment by alexwilliams0712** [comment]
Do we have a timescale at all? What needs doing?

**Comment by altendky** [comment]
Just added https://github.com/aio-libs/yarl/pull/790 to simplify the `pyver:` for 3.11.  Also noted that there isn't a changelog entry for adding 3.11 support.  I'm not sure what PR to credit for it, or maybe multiple, but I found these...

https://github.com/aio-libs/yarl/pull/759
https://github.com/aio-libs/yarl/pull/740
https://github.com/aio-libs/yarl/pull/716
https://github.com/aio-libs/yarl/commit/0c6ec42308d0ec2cab268d236a2f6dc2577fc162

Looks like nothing has changed since v1.8.1 per https://github.com/aio-libs/yarl/compare/v1.8.1..master so I guess any 3.11 wheels could just be added to the v1.8.1 release, if wanted.

Anything I could help with?  Or just need time for the owners to get through the last steps...

**Comment by webknjaz** [comment]
Shipped via v1.8.2
