### ISSUE TITLE
Github Action Linter failing due to out-of-date package 

### ISSUE THREAD

**Issue by dereckt** [aio-libs/yarl#797]
### Describe the bug

As mentioned in #792, the github action that's currently being used as a linter is failing due to it being unable to install "libenchant-dev". I believe the solution to this would be changing "libenchant-dev" to "libenchant-2-dev", since it seems that this is the replacement, but I'm unable to test it on my end.

### To Reproduce

1. Create a fork
2. Change something in fork (add comment) and push to fork.
3. Try to merge fork
4. Wait for maintainers to permit testing
5. Fail pylint check (incorrectly)

### Expected behavior

The linter should run on the PR and correctly check the commit.

### Logs/tracebacks

```python-traceback
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libenchant-dev
Error: Process completed with exit code 100
```

### Python Version

```console
$ python --version
Python 3.10.6
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.0.3
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.8.2
```

### OS

Linux virtual environment.

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by asvetlov** [comment]
Fixed by 1b98176656ecfb96b414c689a18b9586f2103edf
Thank you for filing the bug
