### ISSUE TITLE
regression in URL.build(…,port="") 

### ISSUE THREAD

**Issue by commonism** [aio-libs/yarl#883]
### Describe the bug

Input filtering for with_port #793 changed the logic to render the URL to compare the port to None.
https://github.com/aio-libs/yarl/commit/94b8679da05fd7b2d7bc86ed95e84c09f1946d75#r116844287
as it is possible to create a URL with a port="" via URL.build, this results in urls created with an empty port.

### To Reproduce

```
import yarl
u = yarl.URL.build(scheme="http", host="api.com", port="", path="/v1")
assert str(u) == "http://api.com/v1", str(u)
```

### Expected behavior

Filtering port="" in URL.build.
I'd even prefer to allow "" and convert to None to stay backwards compatible.

### Logs/tracebacks

```python-traceback
AssertionError: http://api.com:/v1
```

### Python Version

```console
$ python --version
Python 3.10.6
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.0.2
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.9.2
```

### OS

Linux

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by webknjaz** [comment]
Hello, please contribute regression tests via PR to move things along.
