### ISSUE TITLE
Planned release?

### ISSUE THREAD

**Issue by Julian** [aio-libs/yarl#922]
### Is your feature request related to a problem?

Hi there! Is a release planned anytime soon?

Because of the workaround for #921 I'm also running into needing #891 (https://github.com/aio-libs/yarl/commit/63dbf3e233438b8cd05d660fae8c8e03a7d0ad34) as `explicit_port` seems to be missing from the type annotations in the most recent release.

Obviously if there's anything I can do to help let me know.

### Describe the solution you'd like

Tag `1.9.3` or `1.10.0` :)

### Describe alternatives you've considered

-

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by davetapley** [comment]
I just created a fork to add `explicit_port` and was very confused when I saw it already in there.
So yes a release would be nice 🤪

**Comment by webknjaz** [comment]
v1.9.3 is out:
- https://pypi.org/project/yarl/1.9.3/
- https://github.com/aio-libs/yarl/discussions/957
- https://github.com/aio-libs/yarl/releases/tag/v1.9.3
